[dbm-api] 17:26:35.357 [main] INFO  com.withlee.dbm.Application - Starting Application on LAPTOP-T7OVDIH0 with PID 7436 (D:\workspaces\dbm-api\target\classes started by think in D:\workspaces\dbm-api)
[dbm-api] 17:26:37.176 [main] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
[dbm-api] 17:26:37.995 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP pool HikariPool-0 is starting.
[dbm-api] 17:26:40.822 [main] INFO  org.apache.catalina.core.StandardService - Starting service Tomcat
[dbm-api] 17:26:40.824 [main] INFO  org.apache.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.0.15
[dbm-api] 17:26:41.025 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
[dbm-api] 17:26:43.398 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8001"]
[dbm-api] 17:26:43.415 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8001"]
[dbm-api] 17:26:43.424 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
[dbm-api] 17:26:43.501 [main] INFO  com.withlee.dbm.Application - Started Application in 8.453 seconds (JVM running for 9.36)
[dbm-api] 17:27:21.817 [http-nio-8001-exec-1] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
[dbm-api] 17:44:59.445 [http-nio-8001-exec-2] ERROR com.withlee.dbm.controller.showapi.Quest_contentController - [getquest_content] - fail to getquest_content Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException: Timeout after 30255ms of waiting for a connection.
[dbm-api] 17:45:29.772 [http-nio-8001-exec-3] ERROR com.withlee.dbm.controller.showapi.Quest_contentController - [getquest_content] - fail to getquest_content Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException: Timeout after 30180ms of waiting for a connection.
